<a href="https://colab.research.google.com/github/weiyixia/CSV-file-repair/blob/master/datacleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('/basicsurvey.parquet')

In [13]:
n_cols = []
for i in list(df.columns):
  if i[:5]!='code:' and i!='What was your biological sex assigned at birth?':
    n_cols.append(i)

In [25]:
rename_cols_dict = {'In what country were you born?':'born_country',
       'Which categories describe you? Select all that apply. Note, you may select more than one group.':'race',
       'What terms best express how you describe your gender identity? (Check all that apply)':'gender',
       'Which of the following best represents how you think of yourself.':'sexual_orientation',
       'What is the highest grade or year of school you completed?':'education',
       'Have you ever served on active duty in the United States Armed forces, either in the regular military or in a National Guard or military reserve unit?':'active_duty',
       'What is your current marital status?':'marital_status',
       'Are you covered by health insurance or some other kind of health care plan?':'insurance_coverage',
       'Are you deaf, or do you have serious difficulty hearing ':'deaf',
       'Are you blind, or do you have serious difficulty seeing, even when wearing glasses':'blind',
       'Because of a physical, mental, or emotional condition, do you have serious difficulty concentrating, remembering, or making decisions':'mental_difficulty',
       'Do you have serious difficulty walking or climbing stairs':'difficulty_walking',
       'Do you have difficulty dressing or bathing':'difficulty_dressing',
       'Because of a physical, mental, or emotional condition, do you have difficulty doing errands alone such as visiting a physician\'s office or shopping':'difficulty_errands',
       'What is your current employment status? Please select 1 or more of these categories.':'employment',
       'What is your annual household income from all sources?':'income',
       'Do you own or rent the place where you live?':'own_or_rent',
       'How many years have you lived at your current address?':'years_in_current_address',
       'In the past 6 months, have you been worried or concerned about NOT having a place to live?':'stable_house_concern'}

In [28]:
df_new = df[n_cols]

In [29]:
df_new.rename(columns=rename_cols_dict, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [30]:
df_new

,born_country,race,gender,sexual_orientation,education,active_duty,marital_status,insurance_coverage,deaf,blind,mental_difficulty,difficulty_walking,difficulty_dressing,difficulty_errands,employment,income,own_or_rent,years_in_current_address,stable_house_concern
0,Birthplace: USA,What Race Ethnicity: Hispanic,Gender Identity: Man,Sexual Orientation: Straight,Highest Grade: Twelve Or GED,Active Duty Serve Status: No,Current Marital Status: Never Married,Health Insurance: No,Deaf: No,Did not answer,Difficulty Concentrating: No,Walking Climbing: Yes,Dressing Bathing: No,Did not answer,Employment Status: Employed For Wages,Annual Income: 10k 25k,Current Home Own: Rent,How Many Living Years: less 1,Stable House Concern: No
1,Birthplace: USA,What Race Ethnicity: White,Gender Identity: Man,Sexual Orientation: Straight,Highest Grade: Twelve Or GED,Active Duty Serve Status: No,Current Marital Status: Married,Health Insurance: Yes,Did not answer,Did not answer,Did not answer,Did not answer,Did not answer,Did not answer,Employment Status: Retired,Annual Income: 10k 25k,Current Home Own: Own,How Many Living Years: 6 to 10,Stable House Concern: Yes
2,Birthplace: USA,What Race Ethnicity: Hispanic,Gender Identity: Man,Sexual Orientation: Straight,Highest Grade: Twelve Or GED,Active Duty Serve Status: No,Current Marital Status: Widowed,Health Insurance: Yes,Did not answer,Did not answer,Did not answer,Did not answer,Did not answer,Did not answer,Employment Status: Retired,Annual Income: more 200k,Current Home Own: Rent,How Many Living Years: less 1,Stable House Concern: No
3,Birthplace: USA,What Race Ethnicity: White,Gender Identity: Woman,Sexual Orientation: Straight,Highest Grade: College One to Three,Active Duty Serve Status: Yes,Current Marital Status: Never Married,Health Insurance: Yes,Deaf: No,Did not answer,Difficulty Concentrating: No,Skip,Did not answer,Errands Alone: No,Employment Status: Retired,Annual Income: 75k 100k,Current Home Own: Rent,How Many Living Years: 11 to 20,Stable House Concern: No
4,Birthplace: USA,What Race Ethnicity: White,Gender Identity: Man,Sexual Orientation: Straight,Highest Grade: College One to Three,Active Duty Serve Status: No,Current Marital Status: Married,Health Insurance: Yes,Deaf: No,Did not answer,Did not answer,Did not answer,Dressing Bathing: No,Did not answer,Employment Status: Retired,Annual Income: more 200k,Current Home Own: Own,How Many Living Years: more 20,Stable House Concern: No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372375,Birthplace: USA,What Race Ethnicity: Hispanic,Gender Identity: Woman,Skip,Highest Grade: Twelve Or GED,Active Duty Serve Status: No,Current Marital Status: Widowed,Health Insurance: Yes,Did not answer,Blind: No,Did not answer,Walking Climbing: No,Dressing Bathing: No,Errands Alone: No,Employment Status: Unable To Work,Annual Income: 35k 50k,Current Home Own: Own,How Many Living Years: 11 to 20,Stable House Concern: No
372376,Birthplace: USA,What Race Ethnicity: Black,Gender Identity: Man,Sexual Orientation: Straight,Highest Grade: College Graduate,Active Duty Serve Status: Yes,Current Marital Status: Married,Health Insurance: Yes,Did not answer,Did not answer,Did not answer,Did not answer,Dressing Bathing: No,Did not answer,Employment Status: Employed For Wages,Prefer Not To Answer,Current Home Own: Rent,How Many Living Years: less 1,Stable House Concern: No
372377,Birthplace: USA,More than one race/ethnicity,Gender Identity: Woman,Sexual Orientation: Straight,Highest Grade: College Graduate,Active Duty Serve Status: No,Current Marital Status: Married,Dont Know,Did not answer,Did not answer,Did not answer,Did not answer,Did not answer,Did not answer,Employment Status: Retired,Annual Income: 50k 75k,Current Home Own: Own,How Many Living Years: 11 to 20,Stable House Concern: No
372378,Birthplace: USA,What Race Ethnicity: Black,Gender Identity: Man,Sexual Orientation: Gay,Highest Grade: Advanced Degree,Active Duty Serve Status: No,Current Marital Status: Never Married,Health Insurance: Yes,Did not answer,Blind: No,Did not answer,Did not answer,Dressing Bathing: No,Did not answer,Employment Status: Out Of Work One Or More,Prefer Not To Answer,Current Home Own: Rent,How Many Living Years: 6 to 10,Stable House Concern: No
372379,Birthplace: USA,What Race Ethnicity: White,Gender Identity: Woman,Sexual Orientation: Straight,Highest Grade: Twelve Or GED,Active Duty Serve Status: No,Current Marital Status: Never Married,Health Insurance: No,Did not answer,Blind: No,Did not answer,Did not answer,Dressing Bathing: No,Did not answer,Employment Status: Self Employed,Annual Income: 75k 100k,Current Home Own: Own,How Many Living Years: less 1,Stable House Concern: No

In [31]:
df_new.to_parquet('/basicsurveycleaned.parquet')